### ISSUE TITLE
Generating help

### ISSUE THREAD

**Issue by briantopping** [skorlir/gulp-load-subtasks#1]
The template that I generated at briantopping/angular2-seed was reviewed by others there and the feedback was that it was not ideal because people could not easily find what tasks were available in one place. While I disagree that's a major issue, it does have merit.

To overcome such objections, it would be helpful that this plugin could generate a list of discovered subtasks. I would imagine this to be done by simply interrogating the `gulp` object after all the tasks were loaded *or* creating a mock `gulp` object that watched for task creation and did the same thing. This list of tasks would be used by a "--help" style flag that output the list.

**Comment by skorlir** [comment]
Do you mean like checking `gulp.tasks`?

**Comment by briantopping** [comment]
Just passing along reasons people don't want to use your library. Check out the comments on https://github.com/mgechev/angular2-seed.

**Comment by skorlir** [comment]
Right, and I'm suggesting that if you want a list of registered tasks, you can inspect `gulp.tasks` after calling `gulp-load-subtasks`.

Also, I'm unsure what you were suggesting I should look at with that link. I checked open issues and I didn't see anything about the library.

**Comment by briantopping** [comment]
I'm noting that as a contributor, I do not have authority to unilaterally overcome objections to get your project into another project workflow. It is one data point. How many projects do you have and how many do you want? Maybe it's a very low number. There's no judgement on my end, you asked for feedback, so I'm trying to give it to you.

**Comment by skorlir** [comment]
Sorry if I seemed standoffish? I was just saying that you said "check out the comments" and I didn't see anything to check out at the link you gave. I do want people to use the library, but I don't think I perfectly understand what you want. No judgment, either. I am thankful for the feedback, and am trying to understand so I can help. :smile:

**Comment by skorlir** [comment]
@briantopping I wanted to be proactive about this, and also wanted to fix something about the library that's been bugging me, so check out the new v1.1.0!

The new `loader.load` returns a list of the absolute paths to each subtask file, and it would not be too difficult to make a mapping of subtask filenames to the subtasks they define. Is that what you were asking for?

I could see making it a `require()`-able feature, for debugging or logging or informational purposes.

**Comment by briantopping** [comment]
Don't worry about it, there's a lot of components of communication. You already did a great thing releasing the library in the first place, no complaints there. In open source, we always get what we paid for and have a money back guarantee :)

In doing a little searching, I also found https://github.com/frankwallis/gulp-hub. This one is interesting because it theoretically will allow multiple files to have the same task name and execute all the tasks with the same name when the task is requested. So for instance, `gulp clean` would find the `clean` task in every sub-build. What's not clear is whether it can handle ordering of these tasks, but that may be simple enough to overcome -- any time there's a dependency, the dependency can be made explicit.

If I hit a dead end with that, I'll give your new stuff a try! Open source is a beautiful thing, keep on trucking and I will see you soon, I presume!  -B

**Comment by skorlir** [comment]
:+1:
