### ISSUE TITLE
Need to pass full path to get glob working

### ISSUE THREAD

**Issue by timkelty** [skorlir/gulp-load-subtasks#3]
To get this working, I had to pass a full path, like so:

```
plugins.loadSubtasks(path.join(__dirname, 'tasks/**/*.js'), plugins);
```

That may be because my directory structure uses a `gulpfile.js` folder, but still seems like I should be able to pass `tasks/**/*.js`:
```
gulpfile.js
├── index.js
└── tasks
    ├── build
    │   ├── css.js
    │   └── js.js
```

**Comment by skorlir** [comment]
I've never seen a gulpfile.js folder before! Cool.

I'll look at this later today, thanks Tim. Is your code available online, by chance?

**Comment by skorlir** [comment]
Just to eliminate the obvious real quick, have you tried passing 'gulpfile.js/tasks/**/*.js'?

**Comment by skorlir** [comment]
Nevermind; I figured it out. The offending line of code incorrectly checks whether a file is a folder by seeing if it has an extension. Should be able to do a quick fix by replacing that with fs.lstatSync().isDirectory().

**Comment by timkelty** [comment]
ah, great! thanks!

**Comment by timkelty** [comment]
Love it. Thanks for the quick fix!

**Comment by skorlir** [comment]
:smile: Of course!

**Comment by timkelty** [comment]
For the record - this didn't fully get it working for me.

The reason is `glob` by default uses `process.cwd` as its starting point. In your examples, your `tasks` folder is right there, so it's not a problem.

So, I still need to either provide the full path, or just provide it relative to process.cwd (so `gulpfile.js/tasks/**/*.js`.

Not sure if there's a good way to make glob call relatively from where your module was called, or if it would even make sense to.

Probably just a note in the docs that the path you pass is always relative to `process.cwd` (if not absolute).

Thanks again!

**Comment by skorlir** [comment]
Right, that would be expected. If your files were named with the pattern "*.tasks.js" it would load them by default given "gulpfile.js/tasks", but since this particular configuration doesn't adhere to the (admittedly opinionated) default you must also specify which files to look for. It's not that much extra work to add in "**/*.js", though!

Concerning `process.cwd`, I think that's a common default to libraries like glob, fs, etc. I'll make a note of it in the README. Thanks.

**Comment by timkelty** [comment]
Yeah - I [briefly looked into](http://stackoverflow.com/questions/13651945/what-is-the-use-of-module-parent-in-node-js-how-can-i-refer-to-the-requireing) how once would get the parent 'calling' path, and it seems that its just not something node really does by convention.

Anyway - totally cool with doing it how I am, was just curious.
