### ISSUE TITLE
Inclusion order

### ISSUE THREAD

**Issue by timkelty** [skorlir/gulp-load-subtasks#4]
Here's what my dir structure looks like:

```
gulpfile.js
├── index.js
└── tasks
    ├── build
    │   ├── css.js
    │   ├── index.js
    │   └── js.js
    ├── lint
    │   ├── css.js
    │   ├── index.js
    │   ├── js.js
    │   └── self.js
    ├── serve
          ├── index.js
          └── watch.js
```

`gulpfile.js/build/index.js` may have something like:

```
module.exports = function (gulp, plugins) {
  var path = require('path');

  gulp.task('build',
    gulp.series('build:css', 'build:js', 'lint:self')
  );
};
```

While `gulpfile.js/build/js.js` may have:
```
module.exports = function(gulp, plugins) {
  gulp.task('build:js', gulp.series(
    function() {
      var path   = require('path');
      var config = require(path.join(process.cwd(), 'gulpfile.js/config'));
      var webpack = require('webpack');

      return gulp.src('dummy.js', { allowEmpty: true })
      .pipe(plugins.webpackStream(config.webpack, webpack))
      .pipe(gulp.dest(config.webpack.output.path));

    },
    'lint:js'
  ));
};
```

I was hoping with this plugin, that I would merely be able to do (in `gulpfile.js/index.js`):
```
plugins.loadSubtasks(
  path.join(__dirname, 'tasks/**/*.js'
), plugins);
```

However, because of how the tasks reference each other, errors like this are thrown. At which point, if I have to call things over again and in order, I may as well just `require` everything.

```
/Users/timkelty/Repos/fusionary-fed/templates/node_modules/gulp-load-plugins/index.js

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Task never defined: lint:js
```

Any suggestions, or alternate approaches are most welcome! Thanks in advance.

**Comment by skorlir** [comment]
So, in this case, the index.js file in each directory needs to be required last?

Let me think about it, but at first glance I think it could be possible to use the subtask loader directly to accomplish this fairly simply. I don't have time to look at it at this exact moment, but I'm on the case. :)

**Comment by timkelty** [comment]
That's correct, index.js last.
On top of that, order can matter (`build` calls `lint`), etc.

I guess I was hoping for a paradigm where I load all the task into one spot and then it if a task was called that wasn't defined, it would load it...but maybe that's more of something that would be part of the `gulp` commands and out of the scope of `gulp-load-subtasks`.

Anyway...thanks for taking a look!

**Comment by skorlir** [comment]
So I've looked this over.

First, I don't think it's in the scope of the plugin to interpret and order your tasks to ensure their dependencies are defined. That sounds like a cool gulp feature, though!

Second, I think you should take a look at [this article about gulp.series and gulp.parallel)[http://fettblog.eu/gulp-4-parallel-and-series/].

It looks to me like your trouble may be coming from trying to force what feels like a gulp 3 dependency structure into the new gulp 4 paradigm, where you should probably minimize the dependencies of your specific tasks and instead offload all that work to your big build tasks. (This also is probably good practice no matter what version of gulp you are using - trying to keep your dependencies as flat as possible only makes things easier to reason about, and moreover makes all those smaller tasks much easier to reuse without accidental side-effects!)

Hope that helps :)

**Comment by timkelty** [comment]
Thanks! That pretty much sums up what I was thinking as well.
